step_index: 1
step_name: step_name
create_time: '2023-06-02T05:54:47.644502'
models:
  HeteroNNGuestMeta:
    sha1: e4cbd2eb5bb417455f1cfa0296a31e85e96f7ae7
    buffer_name: HeteroNNMeta
  HeteroNNGuestParam:
    sha1: 79bd63df607ba60c5303c2e8ff878bde6f070cff
    buffer_name: HeteroNNParam
