step_index: 2
step_name: step_name
create_time: '2023-06-02T05:56:33.662146'
models:
  HeteroNNGuestMeta:
    sha1: e4cbd2eb5bb417455f1cfa0296a31e85e96f7ae7
    buffer_name: HeteroNNMeta
  HeteroNNGuestParam:
    sha1: 1912c67668e09cbd008b9b080499f8fff69480ee
    buffer_name: HeteroNNParam
