step_index: 0
step_name: step_name
create_time: '2023-06-02T05:53:06.005179'
models:
  HeteroNNGuestMeta:
    sha1: e4cbd2eb5bb417455f1cfa0296a31e85e96f7ae7
    buffer_name: HeteroNNMeta
  HeteroNNGuestParam:
    sha1: 341ee8bfd3dfae7e210d8a98c63ea93d136fcdd0
    buffer_name: HeteroNNParam
